pipeline {
    agent {
        node { label 'master' }
    }
    stages {
        stage('Pull code from git hub') {
            steps {
                sh "pwd"
                sh 'git clone https://gitlab.com/osama9mohamed5/devops-task-1.git'
            }
        }
        stage('Build and push app to dockerhub') {
            steps {
                dir("/home/ubuntu/workspace/pipeline/devops-task-1/Second_Challenge") {
                    sh "pwd"
                    sh 'docker build . -t 95osama123/frontend:latest'
                    sh 'docker login -u user -p pass'
                    sh 'docker push 95osama123/frontend:latest'
                }
            }
        }
        stage('Deploy to kubernetes') {
            steps {
                dir("/home/ubuntu/workspace/pipeline/devops-task-1/Second_Challenge/k8s/") {
                    sh "pwd"
                    sh 'kubectl apply -f nodeport.yaml'
                    sh 'kubectl apply -f node-deployment.yaml'
                }
            }
        }
    }
}
